name: giteabot
on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
      - review_requested
      - review_request_removed
      - closed
  pull_request_review:

jobs:
  giteabot:
    runs-on: ubuntu-latest
    steps:
      - uses: go-gitea/giteabot@latest
        with:
          token: ${{ secrets.GITEABOT_TOKEN }}
          repo: ${{ github.repository }}
          provider: github
          api_base: https://api.github.com
          mode: event
          event_path: ${{ github.event_path }}
          event_name: ${{ github.event_name }}